version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Build
          command: echo 'Building... Built!'
  test1:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test 1
          command: echo 'Testing... Tested!!'
  test2:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test 2
          command: echo 'Testing... Tested!!'
  test3:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test 3
          command: echo 'Testing... Tested!!'
workflows:
  version: 2.1
  build-test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - test3:
          requires:
            - test2
